{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.spotbugs",
    "module": "spotbugs",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.5.0"
          }
        },
        {
          "group": "net.jcip",
          "module": "jcip-annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.github.spotbugs",
          "module": "spotbugs-annotations",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "spotbugs-4.4.1.jar",
          "url": "spotbugs-4.4.1.jar",
          "size": 3456369,
          "sha512": "195c7c6147d5b077715460e1edd222ce5d58bfc386618f759d077309dbbd9ca93198609f5b7427b9e6715492e9298060bc9da9cbfe14eabdc09473dd8218d67e",
          "sha256": "48c53d2fdefbcd7292a05e23b50dbaab29047e3c87096e5129e4e7a627c354a3",
          "sha1": "d50cf49af9b5074d5ab3d0f89889d753623f341e",
          "md5": "c51aed4546087c2add61d73d783de304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jaxen",
          "module": "jaxen",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "10.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.5.0"
          }
        },
        {
          "group": "net.jcip",
          "module": "jcip-annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.github.spotbugs",
          "module": "spotbugs-annotations",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "spotbugs-4.4.1.jar",
          "url": "spotbugs-4.4.1.jar",
          "size": 3456369,
          "sha512": "195c7c6147d5b077715460e1edd222ce5d58bfc386618f759d077309dbbd9ca93198609f5b7427b9e6715492e9298060bc9da9cbfe14eabdc09473dd8218d67e",
          "sha256": "48c53d2fdefbcd7292a05e23b50dbaab29047e3c87096e5129e4e7a627c354a3",
          "sha1": "d50cf49af9b5074d5ab3d0f89889d753623f341e",
          "md5": "c51aed4546087c2add61d73d783de304"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotbugs-4.4.1-javadoc.jar",
          "url": "spotbugs-4.4.1-javadoc.jar",
          "size": 7462926,
          "sha512": "328f6ab022bad84ad07658d5465c64ad74cb2c5b3aff486ca8c69817557705349015c633aa7a907c966b04130dbc2321ef9961a6a1298862c472c3a21aa88e93",
          "sha256": "7021a519365315a5fc0f98a0d2c3ed2b73eb20e61baf5b937453b6d085fa02ef",
          "sha1": "fec2c5e9b5f0fddcf6234fa4bfa50360002208cb",
          "md5": "fa726e3af8a4d6dc17c146fefe960cca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotbugs-4.4.1-sources.jar",
          "url": "spotbugs-4.4.1-sources.jar",
          "size": 2332374,
          "sha512": "20b6ba2f9eac600cb412dcc1274ae69378b5896d21f9a88660bc8b44d6e36963e258d2520f29f9d9e2bd124a167e4aac14fe686b867231e0e933693c10991513",
          "sha256": "4e6f932cf21f826d30873b0d51c250d5fc5307fd177ec782d38d82f1019c711d",
          "sha1": "6cce5e7f74d4358c06f174d9d46cb6d79fd1b2a6",
          "md5": "407b8e65bc7b62afd4aeb38d805a366f"
        }
      ]
    }
  ]
}
