/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.htwk.leipzig.grapholution.javafxapp;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test public void testGetMessage() {
        assertEquals("hello      world!", MessageUtils.getMessage());
    }
}
