/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.htwk.leipzig.grapholution.javafxapp;

import de.htwk.leipzig.grapholution.evolibrary.list.LinkedList;

import static de.htwk.leipzig.grapholution.evolibrary.utilities.StringUtils.join;
import static de.htwk.leipzig.grapholution.evolibrary.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(MessageUtils.getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
