/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.htwk.leipzig.grapholution.javafxapp;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
