/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.htwk.leipzig.grapholution.javafxapp;
@Deprecated
class MessageUtils {
    public static String getMessage() {
        return "hello      world!";
    }
}
